spring.application.name=inventory-service

#AWS Config
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.credentials.profile.name=default
#order.confirmed.topic.arn=orderStatusTopicARN
#inventory.allocated.topic.arn=inventoryAllocatedTopicARN
#shipment.received.topic.arn=shipmentReceivedTopicARN
